# both train and infer
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone_better"
    FREEZE_AT: 0 # 0
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    NORM: "SyncBN" # FrozenBN(def), BN, SyncBN
  ANCHOR_GENERATOR:
    ASPECT_RATIOS: [[1.0, 2.0, 3.0]]
  PROPOSAL_GENERATOR:
    MIN_SIZE: 2
  RPN:
    SMOOTH_L1_BETA: 1.0
    IGNORE_IOA: False
    TOP_PROPOSALS_ALL_LEVEL: True
    PRE_NMS_TOPK_TRAIN: 12000
    POST_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
    BOUNDARY_THRESH: -1
    UPDATE_MATCHES: True
    GET_GT_PER_LEVEL: True
    FREEZE_RPN_HEAD: False # def False
  ALLOW_BOX_OUT_OF_BOUNDARY: True
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
    SMOOTH_L1_BETA: 1.0
    ATTENTION: False # def False
  ROI_HEADS:
    NAME: CascadeMutationROIHeads # CascadeROIHeads
    NUM_CLASSES: 1 # to update from 1 -> 2
    IGNORE_IOA: True
    POSITIVE_FRACTION: 0.5
    # NMS_THRESH_TEST: 0.75
  FPN:
    NORM: "BN" # FrozenBN(def), BN, SyncBN
  OVERLAP_BOX_HEAD:
    ENABLE: False # def True
    BUILD_ON_ROI_FEATURE: True
    OVERLAP_IOU_THRESHOLD: 0.4
    REG_LOSS_COEFF: 1.0
    UNIFORM_REG_DIVISOR: True
    PROB_LOSS_BETA: 0.02
INPUT:
  # (?, ) together with MIN_SIZE_TRAIN_SAMPLING = "choice", else (?,?) with "range"
  MIN_SIZE_TRAIN: (850, ) # def=800, short_edge_length
  MIN_SIZE_TEST: 850
  MAX_SIZE_TRAIN: 1400
  MAX_SIZE_TEST: 1400
  CROP:
    ENABLED: True
    TYPE: "relative_range"
    SIZE: [0.7, 0.7]
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  WITH_HOOKS: True # new_parameter
  # RepeatFactorTrainingSampler or TrainingSampler(def)
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
DATASETS:
  TRAIN: ("pedetect_train",)
  TEST:  ("pedetect_val",)
  INFER: ("pedetect_test", )
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.02
  STEPS: (60000, 80000) # (16000, 21400) # 28000,37300 (60000, 78000) 210000, 250000 # new_parameter
  MAX_ITER: 90000 # 24000        # 42000 90000 270000 # new_parameter
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 800
  WARMUP_FACTOR: 0.1
  # LR_SCHEDULER_NAME: "cycle"
  LOSS_WEIGHT_BOX: 1.0    # def 1.0
  LOSS_WEIGHT_LOGIC: 1.0  # def 1.0
TEST:
  EVAL_PERIOD: 2000
  EVAL_START: 30000
  DETECTIONS_PER_IMAGE: 200
SEED: 11301414
OUTPUT_DIR: "./Experiments/detectron2/NewPed/cascade"
