_BASE_: "orig.yaml"
MODEL:
  BACKBONE:
    FREEZE_AT: 0 # 0
  RESNETS:
    NORM: "BN" # "FrozenBN" is default
  RPN:
    FREEZE_RPN_HEAD: False # def False
  ROI_BOX_HEAD:
    ATTENTION: True # def False
  ROI_HEADS:
    NUM_CLASSES: 1 # to update from 1 -> 2
  OVERLAP_BOX_HEAD:
    ENABLE: False # def True
INPUT:
  # (?, ) together with MIN_SIZE_TRAIN_SAMPLING = "choice", else (?,?) with "range"
  MIN_SIZE_TRAIN: (850, ) # def=800, short_edge_length
  MIN_SIZE_TEST: 850
  MAX_SIZE_TRAIN: 1400
  MAX_SIZE_TEST: 1400
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler" # TrainingSampler  RepeatFactorTrainingSampler
# DATASETS:
#   TRAIN: ("ped_train",)
#   TEST: ("ped_val",)
#   INFER: ("ped_test", )
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0001
  CHECKPOINT_PERIOD: 1000
  LR_SCHEDULER_NAME: "cycle"
  LOSS_WEIGHT_BOX: 1.0    # def 1.0
  LOSS_WEIGHT_LOGIC: 1.0  # def 1.0
TEST:
  EVAL_PERIOD: 2000
  EVAL_START: 30000
SEED: 11301414
OUTPUT_DIR: "./Experiments/detectron2/NewPed/trans_cls_head"

